import Head from 'next/head';
import Image from 'next/image'
import { BsTruck } from 'react-icons/bs'
import {IoIosContact}from 'react-icons/io'
import {AiFillTag, AiFillHeart, AiFillStar, AiOutlineMenu} from 'react-icons/ai'
import { FaLinkedin, FaGithub, FaTwitter, FaWallet} from 'react-icons/fa'
import {CgQuote} from 'react-icons/cg'
import {GiDirectorChair, GiTireIronCross} from 'react-icons/gi'
import {MdSettingsSuggest} from 'react-icons/md'
import {SlCalender} from 'react-icons/sl'
import {IoWalletOutline} from 'react-icons/io5'
import {CgArrowLeftR} from 'react-icons/cg'
import { useState, useEffect } from 'react'
import Testimonials from './Navbar'
import  AOS  from 'aos';
import 'aos/dist/aos.css';


function Home() {

  useEffect(() => {
    AOS.init(
    {
    
      easing: 'ease-out',
      once: false,
    }
    );
  },[])

  const [showNav, setShowNav] = useState(false)
  
 
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.icon" />
      </Head>
      <main className=' font-poppins'>
        <section id='header' className="h-auto bg-cover bg-center shadow-lg rounded bg-no-repeat" style={{backgroundImage: "url(/Bg.jpg)", }} >
   
        <nav className='flex justify-between px-10 py-5'>
            <h3 className='flex items-center font-bold text-xl'><GiDirectorChair/> SheddyFurniture</h3>
            {showNav ? (
              <ul className='grid justify-center xl:text-3xl text-center md:-mt-16 md:flex md:font-bold right-0 px-5 xl:px-10 md:justify-end absolute top-0 md:left-0 bg-white md:bg-transparent shadow-lg  py-5' style={{width:'30%', height:'30%'}} onClick={() => setShowNav(false)}>
               <div onClick={() => setShowNav(!showNav)} className='cursor-pointer ml-20'>  <GiTireIronCross/></div>
                <li className='md:px-5 lg:px-10'><a href="#header">Home</a></li>
                <li className='md:px-5 lg:px-10'><a href="#experience">Service</a></li>
                <li className='md:px-5 lg:px-10'><a href="#products1">Gallery</a></li>
                <li className='md:px-5 lg:px-10'><a href="#contact">About</a></li>
              </ul>
            ) : (
              <ul className='hidden md:flex md:justify-center xl:pr-20 font-bold text-xl xl:text-2xl top-0  md:translate-y-0' id='menu'>
                <li className='md:px-5 lg:px-10 hover:bg-blue-950 hover:text-white py-2 rounded-lg'><a href="#header">Home</a></li>
                <li className='md:px-5 lg:px-10 hover:bg-blue-950 hover:text-white py-2 rounded-lg'><a href="#experience">Service</a></li>
                <li className='md:px-5 lg:px-10 hover:bg-blue-950 hover:text-white py-2 rounded-lg'><a href="#products1">Gallery</a></li>
                <li className='md:px-5 lg:px-10 hover:bg-blue-950 hover:text-white py-2 rounded-lg'><a href="#contact">About</a></li>
              </ul>
            )}
            <div onClick={() => setShowNav(!showNav)} className='md:hidden cursor-pointer' id='button'><AiOutlineMenu/></div>
          </nav>
           <div className='text-end lg:text-center py-10 md:mt-20 mr-5  '>
            <h1 className='text-3xl p-2 font-bold font-Alkatra'>Simplify your Home</h1>
            <p className='block pb-5 text-xl lg:text-2xl md:pr-5'>Experience the perfect blend of form and function with our <br/>premium quality furniture collection.</p>
            <div className=' p-10 pt-10 flex justify-evenly'>
              <button className='bg-blue-950 px-3 py-2 text-white rounded-lg hover:shadow-lg hover:bg-transparent hover:border hover:border-blue-950 hover:text-black'>Shop Now</button>
              <button className=' px-3 py-2 border border-blue-950 rounded-lg hover:shadow-lg hover:bg-blue-950 hover:text-white'>Explore</button>
            </div>
           </div>
         </section>
         {/*--------- experience---------------- */}
        <section >
       <div data-aos="fade-down"  className='lg:flex gap-3 justify-center' >
       <div className='grid justify-center text-center shadow-lg h-100 m-5 p-10'>
            <div className=' p-3 w-10 bg-gray-400  rounded-md flex justify-center mt-4 mx-auto'><IoIosContact /></div>
            <h1 className=' text-xl font-bold mt-4'>2+ years experience</h1>
            <p className='text-xl'>Most expereince furniture seller at your doorstep</p>
          </div>
          <div className=' grid justify-center text-center shadow-lg h-100 m-5 p-10'>
            <div className=' p-3 w-10 text-white rounded-md flex justify-center mt-4 mx-auto bg-blue-950'><SlCalender /></div>
            <h1 className='font-bold mt-4 text-xl'>2k+ Happy clients</h1>
            <p className='text-xl'>A happy client is the pride at sheddyfurniture</p>
          </div>
          <div className=' grid justify-center text-center shadow-lg h-100 m-5 p-10'>
            <div className=' p-3 w-10 bg-gray-400  rounded-md flex justify-center mt-4 mx-auto'><SlCalender  /></div>
            <h1 className='text-xl  font-bold mt-4'>500+ projects Finished</h1>
            <p className='text-xl '>Finished more that 500 projects in your city</p>
          </div>
       </div>
       <div id='experience' className='lg:flex grid justify-center md:gap-3 m-auto mt-10'>
            <Image  data-aos="fade-right" src={'/firstImg.jpg'} width={600} height={600} className='lg:m-0 rounded-xl h-100 w-100 object-cover lg:basis-1/2'/>
            <div data-aos="fade-left" className='lg:text-start lg:mx-auto'>
              <h3 className='mt-5 lg:text-lg'>our services</h3>
              <h1 className='text-xl lg:text-2xl font-bold'>Feel the best experience with our sofa deals</h1>
             <div className='flex gap-4 mt-8 xl:text-2xl lg:pb-5'> 
              <div className=' shadow-lg border-4 border-white bg-gray-400 flex items-center px-5 py-5 my-auto rounded-xl '>
                <AiFillTag className='rounded-xl text-blue-950'/>
              </div>
              <div >
                <h2 className='font-bold max-w-xl text-start'>Smile for every budget</h2>
                <p>All chairs are budget friendly</p>
              </div>
              </div>
             <div className='flex gap-4 mt-8 xl:text-2xl lg:pb-5'> 
              <div className=' shadow-lg border-4 border-white bg-gray-400 flex items-center px-5 py-5 my-auto rounded-xl '>
                <FaWallet className='text-blue-950' />
              </div>
              <div>
                <h2 className=' font-bold max-w-xl text-start'>Best price Guarantee</h2>
                <p>The best price you can get </p>
              </div>
              </div>
             <div className='flex gap-4 mt-8 xl:text-2xl'> 
              <div className=' bg-gray-400 flex items-center px-5 py-5 my-auto shadow-lg border-4 border-white rounded-xl '>
                <MdSettingsSuggest className='text-blue-950'/>
              </div>
              <div>
                <h2 className='font-bold max-w-xl text-start'>Support 24/7</h2>
                <p>Customer care service always available</p>
              </div>
              </div>

            </div>
          </div>
          <div data-aos="fade-down" className='flex justify-evenly mt-20'>
          <div className='grid justify-start pl-4'>
            <div className='w-20 m-auto flex justify-center rounded-full p-5 bg-gray-400'>
              <BsTruck className='w-10 h-10'/></div>
            <h1 className='font-bold p-2 text-xl text-center'>Fast Delivery</h1>
           <p className=' text-center '>We have fast Delivery service that gets to you in no time.</p>
          < a href="#" className=' underline text-center font-bold p-2'>Read Me</a>
          </div>
          <div className='grid justify-start pl-4'>
            <div className='w-20 m-auto flex justify-center rounded-full p-5  bg-gray-400'>
              <IoWalletOutline className=' color-white  w-10 h-10 '/></div>
            <h1 className='font-bold p-2 text-xl text-center'>Secure Payment</h1>
           <p className=' text-center '>Our payments policies are verified and therefore accountable</p>
          < a href="#" className=' underline text-center font-bold p-2'>Read Me</a>
          </div>
          <div className=' grid justify-start pl-4'>
            <div className='w-20 m-auto rounded-full p-5 bg-gray-400'>
              <CgArrowLeftR className=' w-10 h-10'/></div>
            <h1 className='font-bold p-2 text-xl text-center'>14 days return</h1>
           <p className='  text-center'>we give a 14 day return policy incase a bug is found.</p>
          < a href="#" className=' underline text-center font-bold p-2'>Read Me</a>
          </div>
          </div>
        </section>
        <h1 className='text-center mt-10 font-bold text-xl p-3'>Best Selling Products</h1>
        <section data-aos-once="true" id='products1'>
          <div data-aos="fade-up" className='grid xl:grid-cols-4 md:grid-cols-2 lg:grid-cols-3 justify-evenly mx-auto'>
          <div  className='inline-block text-center'>
          <div className='mt-5 mb-3 ml-5 min-h-100 border rounded-lg shadow-lg' style={{ display: 'inline-block' }}>
            <Image src={'/img1.jpg'} width={300} height={300} className='block ' style={{ objectFit: 'fill', width: '300px', height: '15rem' }}/>
            <div className='flex items-center justify-around'>
            <div className='text-start'>
              <p className='pt-2'>sofa</p>
              <h1 className='font-bold pt-2'>Minimalistic sofa</h1>
              <h3 className='pb-2'>$1200 <span className='text-xs'>/items</span></h3>
            </div>
            <AiFillHeart className=' text-red-500'/>
            </div>
          </div>
            <ul className='flex text-xs justify-center'>
              <li className='pl-4'>100% polyester</li>
              <li className='pl-4'>Best Quality</li>
              <li className='pl-4'>30 days return</li>
            </ul>
            <button className=' bg-blue-950 text-white mt-3 font-bold px-20 py-3 rounded-xl' style={{ display: 'inline-block' }}>Buy now</button>          </div>
          <div className='inline-block text-center'>
          <div className='mt-5 mb-3 ml-5 min-h-100 border rounded-lg shadow-lg' style={{ display: 'inline-block' }}>
            <Image src={'/img3.jpg'} width={300} height={300} className='block ' style={{ objectFit: 'fill', width: '300px', height: '15rem' }}/>
            <div className='flex items-center justify-around'>
            <div className='text-start'>
              <p className='pt-2'>sofa</p>
              <h1 className='font-bold pt-2'>Minimalistic sofa</h1>
              <h3 className='pb-2'>$1200 <span className='text-xs'>/items</span></h3>
            </div>
            <AiFillHeart className=' text-red-500'/>
            </div>
          </div>
            <ul className='flex text-xs justify-center'>
              <li className='pl-4'>100% polyester</li>
              <li className='pl-4'>Best Quality</li>
              <li className='pl-4'>30 days return</li>
            </ul>
            <button className=' bg-blue-950 text-white mt-3 font-bold px-20 py-3 rounded-xl' style={{ display: 'inline-block' }}>Buy now</button>          </div>
          <div className='inline-block text-center'>
          <div className='mt-5 mb-3 ml-5 min-h-100 border rounded-lg shadow-lg' style={{ display: 'inline-block' }}>
            <Image src={'/img4.jpg'} width={300} height={100} className='block ' style={{ objectFit: 'fill', width: '300px', height: '15rem' }}/>
            <div className='flex items-center justify-around'>
            <div className='text-start'>
              <p className='pt-2'>sofa</p>
              <h1 className='font-bold pt-2'>Minimalistic sofa</h1>
              <h3 className='pb-2'>$1200 <span className='text-xs'>/items</span></h3>
            </div>
            <AiFillHeart className=' text-red-500'/>
            </div>
          </div>
            <ul className='flex text-xs justify-center'>
              <li className='pl-4'>100% polyester</li>
              <li className='pl-4'>Best Quality</li>
              <li className='pl-4'>30 days return</li>
            </ul>
            <button className=' bg-blue-950 text-white mt-3 font-bold px-20 py-3 rounded-xl' style={{ display: 'inline-block' }}>Buy now</button>          </div>
          <div  className='inline-block text-center'>
          <div className='mt-5 mb-3 ml-5 min-h-100 border rounded-lg shadow-lg' style={{ display: 'inline-block' }}>
            <Image src={'/img18.jpg'} width={300} height={100} className='block ' style={{ objectFit: 'fill', width: '300px', height: '15rem' }}/>
            <div className='flex items-center justify-around'>
            <div className='text-start'>
              <p className='pt-2'>sofa</p>
              <h1 className='font-bold pt-2'>Minimalistic sofa</h1>
              <h3 className='pb-2'>$1200 <span className='text-xs'>/items</span></h3>
            </div>
            <AiFillHeart className=' text-red-500'/>
            </div>
          </div>
            <ul className='flex text-xs justify-center'>
              <li className='pl-4'>100% polyester</li>
              <li className='pl-4'>Best Quality</li>
              <li className='pl-4'>30 days return</li>
            </ul>
            <button className=' bg-blue-950 text-white mt-3 font-bold px-20 py-3 rounded-xl' style={{ display: 'inline-block' }}>Buy now</button>          </div>
          <div className='inline-block text-center'>
          <div className='mt-5 mb-3 ml-5 min-h-100 border rounded-lg shadow-lg' style={{ display: 'inline-block' }}>
            <Image src={'/img6.jpg'} width={300} height={100} className='block ' style={{ objectFit: 'fill', width: '300px', height: '15rem' }}/>
            <div className='flex items-center justify-around'>
            <div className='text-start'>
              <p className='pt-2'>sofa</p>
              <h1 className='font-bold pt-2'>Minimalistic sofa</h1>
              <h3 className='pb-2'>$1200 <span className='text-xs'>/items</span></h3>
            </div>
            <AiFillHeart className=' text-red-500'/>
            </div>
          </div>
            <ul className='flex text-xs justify-center'>
              <li className='pl-4'>100% polyester</li>
              <li className='pl-4'>Best Quality</li>
              <li className='pl-4'>30 days return</li>
            </ul>
            <button className=' bg-blue-950 text-white mt-3 font-bold px-20 py-3 rounded-xl' style={{ display: 'inline-block' }}>Buy now</button>          </div>
          <div className='inline-block text-center'>
          <div className='mt-5 mb-3 ml-5 min-h-100 border rounded-lg shadow-lg' style={{ display: 'inline-block' }}>
            <Image src={'/img7.jpg'} width={300} height={100} className='block ' style={{ objectFit: 'fill', width: '300px', height: '15rem' }}/>
            <div className='flex items-center justify-around'>
            <div className='text-start'>
              <p className='pt-2'>sofa</p>
              <h1 className='font-bold pt-2'>Minimalistic sofa</h1>
              <h3 className='pb-2'>$1200 <span className='text-xs'>/items</span></h3>
            </div>
            <AiFillHeart className=' text-red-500'/>
            </div>
          </div>
            <ul className='flex text-xs justify-center'>
              <li className='pl-4'>100% polyester</li>
              <li className='pl-4'>Best Quality</li>
              <li className='pl-4'>30 days return</li>
            </ul>
            <button className=' bg-blue-950 text-white mt-3 font-bold px-20 py-3 rounded-xl' style={{ display: 'inline-block' }}>Buy now</button>          </div>
          <div className='inline-block text-center'>
          <div className='mt-5 mb-3 ml-5 min-h-100 border rounded-lg shadow-lg' style={{ display: 'inline-block' }}>
            <Image src={'/img8.jpg'} width={300} height={100} className='block ' style={{ objectFit: 'fill', width: '300px', height: '15rem' }}/>
            <div className='flex items-center justify-around'>
            <div className='text-start'>
              <p className='pt-2'>sofa</p>
              <h1 className='font-bold pt-2'>Minimalistic sofa</h1>
              <h3 className='pb-2'>$1200 <span className='text-xs'>/items</span></h3>
            </div>
            <AiFillHeart className=' text-red-500'/>
            </div>
          </div>
            <ul className='flex text-xs justify-center'>
              <li className='pl-4'>100% polyester</li>
              <li className='pl-4'>Best Quality</li>
              <li className='pl-4'>30 days return</li>
            </ul>
            <button className=' bg-blue-950 text-white mt-3 font-bold px-20 py-3 rounded-xl' style={{ display: 'inline-block' }}>Buy now</button>          </div>
          <div className='inline-block text-center'>
          <div className='mt-5 mb-3 ml-5 min-h-100 border rounded-lg shadow-lg' style={{ display: 'inline-block' }}>
            <Image src={'/img9.jpg'} width={300} height={100} className='block ' style={{ objectFit: 'fill', width: '300px', height: '15rem' }}/>
            <div className='flex items-center justify-around'>
            <div className='text-start'>
              <p className='pt-2'>sofa</p>
              <h1 className='font-bold pt-2'>Minimalistic sofa</h1>
              <h3 className='pb-2'>$1200 <span className='text-xs'>/items</span></h3>
            </div>
            <AiFillHeart className=' text-red-500'/>
            </div>
          </div>
            <ul className='flex text-xs justify-center'>
              <li className='pl-4'>100% polyester</li>
              <li className='pl-4'>Best Quality</li>
              <li className='pl-4'>30 days return</li>
            </ul>
            <button className=' bg-blue-950 text-white mt-3 font-bold px-20 py-3 rounded-xl' style={{ display: 'inline-block' }}>Buy now</button>
          </div>
          </div>
         <div className='text-center py-10'>
         <button className=' bg-blue-950 text-white mx-a mt-3 font-bold px-40  py-3 rounded-3xl inline-block'>See More</button>
           <h2 className='mt-7 font-bold text-2xl'>Your Favourites</h2>
         </div>
         <div  data-aos="fade-down" id='product2' className='grid xl:grid-cols-4 md:grid-cols-2 lg:grid-cols-3 justify-evenly mx-auto'>
          <div className='inline-block text-center'>
          <div className='mt-5 mb-3 ml-5 min-h-100 border rounded-lg shadow-lg' style={{ display: 'inline-block' }}>
            <Image src={'/img10.jpg'} width={300} height={100} className='block ' style={{ objectFit: 'fill', width: '300px', height: '15rem' }}/>
            <div className='flex items-center justify-around'>
            <div className='text-start'>
              <p className='pt-2'>sofa</p>
              <h1 className='font-bold pt-2'>Minimalistic sofa</h1>
              <h3 className='pb-2'>$1200 <span className='text-xs'>/items</span></h3>
            </div>
            <AiFillHeart className=' text-red-500'/>
            </div>
          </div>
            <ul className='flex text-xs justify-center'>
              <li className='pl-4'>100% polyester</li>
              <li className='pl-4'>Best Quality</li>
              <li className='pl-4'>30 days return</li>
            </ul>
            <button className=' bg-blue-950 text-white mt-3 font-bold px-20 py-3 rounded-xl' style={{ display: 'inline-block' }}>Buy now</button>
          </div>
          <div className='inline-block text-center'>
          <div className='mt-5 mb-3 ml-5 min-h-100 border rounded-lg shadow-lg' style={{ display: 'inline-block' }}>
            <Image src={'/img11.jpg'} width={300} height={100} className='block ' style={{ objectFit: 'fill', width: '300px', height: '15rem' }}/>
            <div className='flex items-center justify-around'>
            <div className='text-start'>
              <p className='pt-2'>sofa</p>
              <h1 className='font-bold pt-2'>Minimalistic sofa</h1>
              <h3 className='pb-2'>$1200 <span className='text-xs'>/items</span></h3>
            </div>
            <AiFillHeart className=' text-red-500'/>
            </div>
          </div>
            <ul className='flex text-xs justify-center'>
              <li className='pl-4'>100% polyester</li>
              <li className='pl-4'>Best Quality</li>
              <li className='pl-4'>30 days return</li>
            </ul>
            <button className=' bg-blue-950 text-white mt-3 font-bold px-20 py-3 rounded-xl' style={{ display: 'inline-block' }}>Buy now</button>
          </div>
          <div className='inline-block text-center'>
          <div className='mt-5 mb-3 ml-5 min-h-100 border rounded-lg shadow-lg' style={{ display: 'inline-block' }}>
            <Image src={'/img12.jpg'} width={300} height={100} className='block ' style={{ objectFit: 'fill', width: '300px', height: '15rem' }}/>
            <div className='flex items-center justify-around'>
            <div className='text-start'>
              <p className='pt-2'>sofa</p>
              <h1 className='font-bold pt-2'>Minimalistic sofa</h1>
              <h3 className='pb-2'>$1200 <span className='text-xs'>/items</span></h3>
            </div>
            <AiFillHeart className=' text-red-500'/>
            </div>
          </div>
            <ul className='flex text-xs justify-center'>
              <li className='pl-4'>100% polyester</li>
              <li className='pl-4'>Best Quality</li>
              <li className='pl-4'>30 days return</li>
            </ul>
            <button className=' bg-blue-950 text-white mt-3 font-bold px-20 py-3 rounded-xl' style={{ display: 'inline-block' }}>Buy now</button>
          </div>
          <div className='inline-block text-center'>
          <div className='mt-5 mb-3 ml-5 min-h-100 border rounded-lg shadow-lg' style={{ display: 'inline-block' }}>
          <Image src={'/img19.jpg'} width={300} height={100} className='block ' style={{ objectFit: 'fill', width: '300px', height: '15rem' }}/>
            <div className='flex items-center justify-around'>
            <div className='text-start'>
              <p className='pt-2'>sofa</p>
              <h1 className='font-bold pt-2'>Minimalistic sofa</h1>
              <h3 className='pb-2'>$1200 <span className='text-xs'>/items</span></h3>
            </div>
            <AiFillHeart className=' text-red-500'/>
            </div>
          </div>
            <ul className='flex text-xs justify-center'>
              <li className='pl-4'>100% polyester</li>
              <li className='pl-4'>Best Quality</li>
              <li className='pl-4'>30 days return</li>
            </ul>
            <button className=' bg-blue-950 text-white mt-3 font-bold px-20 py-3 rounded-xl' style={{ display: 'inline-block' }}>Buy now</button>
          </div>
          <div className='inline-block text-center'>
          <div className='mt-5 mb-3 ml-5 min-h-100 border rounded-lg shadow-lg' style={{ display: 'inline-block' }}>
            <Image src={'/img14.jpg'} width={300} height={100} className='block ' style={{ objectFit: 'fill', width: '300px', height: '15rem' }}/>
            <div className='flex items-center justify-around'>
            <div className='text-start'>
              <p className='pt-2'>sofa</p>
              <h1 className='font-bold pt-2'>Minimalistic sofa</h1>
              <h3 className='pb-2'>$1200 <span className='text-xs'>/items</span></h3>
            </div>
            <AiFillHeart className=' text-red-500'/>
            </div>
          </div>
            <ul className='flex text-xs justify-center'>
              <li className='pl-4'>100% polyester</li>
              <li className='pl-4'>Best Quality</li>
              <li className='pl-4'>30 days return</li>
            </ul>
            <button className=' bg-blue-950 text-white mt-3 font-bold px-20 py-3 rounded-xl' style={{ display: 'inline-block' }}>Buy now</button>
          </div>
          <div className='inline-block text-center'>
          <div className='mt-5 mb-3 ml-5 min-h-100 border rounded-lg shadow-lg' style={{ display: 'inline-block' }}>
            <Image src={'/img15.jpg'} width={300} height={100} className='block ' style={{ objectFit: 'fill', width: '300px', height: '15rem' }}/>
            <div className='flex items-center justify-around'>
            <div className='text-start'>
              <p className='pt-2'>sofa</p>
              <h1 className='font-bold pt-2'>Minimalistic sofa</h1>
              <h3 className='pb-2'>$1200 <span className='text-xs'>/items</span></h3>
            </div>
            <AiFillHeart className=' text-red-500'/>
            </div>
          </div>
            <ul className='flex text-xs justify-center'>
              <li className='pl-4'>100% polyester</li>
              <li className='pl-4'>Best Quality</li>
              <li className='pl-4'>30 days return</li>
            </ul>
            <button className=' bg-blue-950 text-white mt-3 font-bold px-20 py-3 rounded-xl' style={{ display: 'inline-block' }}>Buy now</button>
          </div>
          <div className='inline-block text-center'>
          <div className='mt-5 mb-3 ml-5 min-h-100 border rounded-lg shadow-lg' style={{ display: 'inline-block' }}>
            <Image src={'/img16.jpg'} width={300} height={100} className='block ' style={{ objectFit: 'fill', width: '300px', height: '15rem' }}/>
            <div className='flex items-center justify-around'>
            <div className='text-start'>
              <p className='pt-2'>sofa</p>
              <h1 className='font-bold pt-2'>Minimalistic sofa</h1>
              <h3 className='pb-2'>$1200 <span className='text-xs'>/items</span></h3>
            </div>
            <AiFillHeart className=' text-red-500'/>
            </div>
          </div>
            <ul className='flex text-xs justify-center'>
              <li className='pl-4'>100% polyester</li>
              <li className='pl-4'>Best Quality</li>
              <li className='pl-4'>30 days return</li>
            </ul>
            <button className=' bg-blue-950 text-white mt-3 font-bold px-20 py-3 rounded-xl' style={{ display: 'inline-block' }}>Buy now</button>
          </div>
          <div className='inline-block text-center'>
          <div className='mt-5 mb-3 ml-5 min-h-100 border rounded-lg shadow-lg' style={{ display: 'inline-block' }}>
            <Image src={'/img17.jpg'} width={300} height={100} className='block ' style={{ objectFit: 'fill', width: '300px', height: '15rem' }}/>
            <div className='flex items-center justify-around'>
            <div className='text-start'>
              <p className='pt-2'>sofa</p>
              <h1 className='font-bold pt-2'>Minimalistic sofa</h1>
              <h3 className='pb-2'>$1200 <span className='text-xs'>/items</span></h3>
            </div>
            <AiFillHeart className=' text-red-500'/>
            </div>
          </div>
            <ul className='flex text-xs justify-center'>
              <li className='pl-4'>100% polyester</li>
              <li className='pl-4'>Best Quality</li>
              <li className='pl-4'>30 days return</li>
            </ul>
            <button className=' bg-blue-950 text-white mt-3 font-bold px-20 py-3 rounded-xl' style={{ display: 'inline-block' }}>Buy now</button>
          </div>
          </div>
        </section>
         {/* Blog Entries */}
        <section id='blogs'>
          <div data-aos="fade-down" className=' text-center mt-10'>
             <button className=' bg-blue-950 text-white font-bold px-40 py-3 rounded-3xl inline-block'>See More</button>
             <h1 className='p-6 font-bold text-2xl'>Blog Entries</h1>
            <div className='flex justify-center'>
            <p className=' max-w-xl'>Discover the perfect blend of style and functionality with our exquisite collection of furniture pieces. Elevate your living space today.</p>
            </div>
          </div>  
          <div className='grid grid-rows-1 justify-center md:grid md:grid-cols-2 xl:grid-cols-3'>
            <div data-aos="fade-left" className='m-10 inline-block'>
              <Image src={'/Img2.jpg'} width={500} height={100} className='rounded-xl'/>
              <div className='text-center'>
              <h1 className='font-bold p-4'>Comfortable Cusions Monseuir</h1>
              <p className='max-w-lg'>Indulge in ultimate relaxation with our plush recliner chairs, designed for maximum comfort and support. Find your perfect recliner today!.</p>
              <button className=' bg-blue-950 text-white mt-4 font-bold px-10 py-3 rounded-xl shadow-lg shadow-black' style={{ display: 'inline-block'}}>Read More</button>
              </div>
            </div>
            <div data-aos="fade-right" className='m-10 inline-block'>
              <Image src={'/Img19.jpg'} width={500} height={100} className='rounded-xl'/>
              <div className='text-center'>
              <h1 className='font-bold p-4'>Accent Chair Monseuir</h1>
              <p className='max-w-lg'>Make a bold statement with our stunning accent chairs, featuring unique designs and eye-catching patterns. Elevate your living space with style.</p>
              <button className=' bg-blue-950 text-white mt-4 font-bold px-10 py-3 rounded-xl shadow-lg shadow-black' style={{ display: 'inline-block'}}>Read More</button>
              </div>
            </div>
            <div data-aos="fade-left" className='m-10 inline-block'>
              <Image src={'/Img21.jpg'} width={500} height={100} className=' w-50 rounded-xl'/>
              <div className='text-center'>
              <h1 className='font-bold p-4'>Office Cusions Monseuir</h1>
              <p className='max-w-lg'>Stay comfortable and productive with our ergonomic office chairs, designed to support your posture and alleviate back pain. Upgrade your workspace today!.</p>
              <button className=' bg-blue-950 text-white mt-4 font-bold px-10 py-3 rounded-xl shadow-lg shadow-black' style={{ display: 'inline-block'}}>Read More</button>
              </div>
            </div>
          </div>
          <div data-aos="fade-down" className='md:justify-evenly items-center'>
            <div className='text-center mt-5 mb-5'>
            <Testimonials />
            </div>
           
          </div>
          {/* --------Testimonia session--------- */}
          <div className='grid md:grid-cols-2 xl:grid-cols-3 justify-center '>
            <div data-aos="fade-left" className='m-5 shadow-lg inline-block'>
              <h1><CgQuote className='text-6xl'/></h1>
              <p className='max-w-sm'>I purchased a sofa from SheddyFurniture and I'm blown away by the quality and comfort. It's become the centerpiece of my living room.</p>
              <div className='flex items-center justify-between mt-4 mb-4'>
                <div className='flex p-2'>
                <Image src={'/Me.jpg'} width={60} height={50} className=' rounded-full w-10 mr-2'/>
                <div><h1>Musa Shedrach</h1> 
                <p>Front-end Developer</p></div>
                </div>
                <div className='flex text-yellow-400'>
                  <AiFillStar/>
                  <AiFillStar/>
                  <AiFillStar/>
                  <AiFillStar/>
                  <AiFillStar/>
                </div>
              </div>
            </div>
            <div data-aos="fade-right" className='m-5 shadow-lg inline-block'>
              <h1><CgQuote className='text-6xl'/></h1>
              <p className='max-w-sm'>I needed a custom-made bed frame and SheddyFurniture delivered exactly what I wanted. Their attention to detail is unparalleled!</p>
              <div className='flex items-center justify-between mt-4 mb-4'>
                <div className='flex p-2'>
                <Image src={'/person1.jpg'} width={60} height={50} className=' rounded-full w-10 mr-2'/>
                <div><h1>Thanos</h1> 
                <p>Villain that retired</p></div>
                </div>
                <div className='flex text-yellow-400'>
                  <AiFillStar/>
                  <AiFillStar/>
                  <AiFillStar/>
                  <AiFillStar/>
                  <AiFillStar/>
                </div>
              </div>
            </div>
            <div data-aos="fade-left" className='m-5 shadow-lg inline-block'>
              <h1><CgQuote className='text-6xl'/></h1>
              <p className='max-w-sm'>I recently furnished my entire house with SheddyFurniture and I couldn't be happier. The furniture is not only beautiful but also functional and durable.</p>
              <div className='flex items-center justify-between mt-4 mb-4'>
                <div className='flex p-2'>
                <Image src={'/person2.jpg'} width={60} height={50} className=' rounded-full w-10 mr-2'/>
                <div><h1>Captain America</h1> 
                <p>Hero of The United States</p></div>
                </div>
                <div className='flex text-yellow-400'>
                  <AiFillStar/>
                  <AiFillStar/>
                  <AiFillStar/>
                  <AiFillStar/>
                  <AiFillStar/>
                </div>
              </div>
            </div>
          </div>
        </section>
        {/* ------contact Section--------- */}
        <section id='contact'>
          <div data-aos="fade-down" className='text-center grid justify-center my-5'>
            <h1 className='font-bold text-lg'>Talk To Us</h1>
            <p className='max-w-lg m-5'>Our team of furniture experts are here to assist you. Chat with us today and let us help you find your perfect piece!</p>
          </div>
          <div data-aos="fade-left" className='grid justify-center gap-5 md:flex md:justify-evenly mt-8'>
            <div>
              <h1 className='font-bold text-lg'>Keep in touch</h1>
              <p className='max-w-lg pt-3'>Transform your living space into a stunning sanctuary with our exquisite range of furniture pieces. Shop now and elevate your home!</p>
              <p className='max-w-lg pt-3'>Experience the perfect blend of form and function with our premium quality furniture collection. Find the pieces that suit your style today!</p>
            </div>
            <form className='grid justify-start gap-5 mb-5'>
              <label className='flex gap-5'>
              <input type="text" placeholder='Full Name' className=' bg-gray-300 border px-5 py-2.5 rounded-3xl placeholder-blue-950' />
              <input type="text" placeholder='Email Address' className=' bg-gray-300 border rounded-3xl px-5 py-2.5 placeholder-blue-950' />
              </label>
              <label htmlFor="">
                <textarea cols="51" rows="5" className=' bg-gray-300 border rounded-xl pr-20 p-2 placeholder-blue-950' placeholder='Your Message'></textarea>
              </label>
              <button className='flex bg-blue-950 text-white font-bold px-4 py-3 mr-auto rounded-3xl '>Send Message</button>
            </form>
          </div>
          <div data-aos="fade-up" className='flex mt-16'>
            <div class="absolute z-2 bg-blue-950 rounded-xl my-20" style={{left:'10%', gridArea: 'overlap', height: '500px', width: '80%'}}>
              <div className='xl:flex text-white text-center grid gap-3 grid-cols-2 tracking-widest mt-40'>
                <div className='ml-5'>
                  <h1 className='xl:py-3 font-bold text-2xl text-start '>SheddyFurniture</h1>
                  <p className=' py-3 max-w-sm text-start'>Discover the perfect blend of style and functionality with our exquisite collection of furniture pieces. Elevate your living space today.?</p>
                </div>
                <div>
                  <h1 className='font-bold text-xl xl:py-3'>Company</h1>
                  <ul className='py-3'>
                    <li className='xl:p-1'>Home</li>
                    <li className='xl:p-1'>Service</li>
                    <li className='xl:p-1'>About</li>
                    <li className='xl:p-1'>Contact</li>
                  </ul>
                </div>
                <div className='grid justify-start ml-5 text-start'>
                  <h1 className='font-bold text-xl py-3'>Support</h1>
                  <ul className=''>
                    <li className='xl:p-1'>Our Team</li>
                    <li className='xl:p-1'>Partner with us</li>
                    <li className='xl:p-1'>FAQ</li>
                    <li className='xl:p-1'>Privacy Policy</li>
                  </ul>
                </div>
                <div>
                  <h1 className='font-bold text-xl justify-center xl:py-3'>Follow Us</h1>
                  <ul className='grid justify-center xl:gap-4 xl:p-3'>
                    <li className='py-1 underline '><a className='flex gap-2 items-center' href="https://github.com/sheddy450?tab=repositories"><FaGithub/>Github</a></li>
                    <li className='py-1 underline'><a className='flex gap-2 items-center' href="https://www.linkedin.com/in/shedrach-musa-a6b182231"><FaLinkedin/>Linkedin</a></li>
                    <li className='py-1 underline'><a className='flex gap-2 items-center' href="https://twitter.com/kungfu_sheddy?t=J4_If_1O7myF67cCSiTDPQ&s=09"><FaTwitter/>Twitter</a></li>
                  </ul>
                </div>
              </div>
            </div>
            <div class="grid justify-center relative  mx-auto bg-white rounded-xl " style={{ gridArea: 'overlap', height: '200px', width: '50%'}}>
              <h1 className='text-center font-bold md:text-xl lg:text-3xl max-w-xl'>Subscribe For Any News Updates From SheddyFurniture</h1>
              <input type="text" className=' border-b-4 mb-4 mx-7 border-blue-950 placeholder-blue-950 placeholder' placeholder='Enter your Email'/>
              <button className=' bg-blue-950 px-5 mb-2 text-white font-bold rounded-3xl mx-auto'>Subscribe</button>
              </div>
          </div>
        </section>
      </main>
    </div>
  )
}
export default Home;
